### ISSUE TITLE
Fazer levantamento de requisitos

### ISSUE THREAD

**Issue by germanotm** [germanotm/cursaqui#1]
Fazer o levantamento de requisitos do sistema e criar issues para as novas funcionalidades assim a gente pode ir desenvolvendo.
O passo 2 do readme.md já tem algumas coisas que podem virar issues.

**Comment by danielshark00** [comment]
Manter Eventos.
- O sistema deve permitir manter um evento e associar vários eventos a ele mesmo.
- O evento terá situações como Ativo/Inativo.
- Cada evento deverá ter um responsável, ele poderá realizar alterações de Calendário e informar a presença dos participantes. Qualquer modificação nos eventos que é responsável ele deverá ser notificado. Caso optemos por ter um Administrador dessa Instituição.
- Dentro de cada evento será parametrizado o número de participantes permitidos.
- Dentro de cada evento será informado o tema, o nível de detalhamento/dificuldade e mini currículo do palestrante (será que integramos com Linkedin?)
- Para cada evento será informado o Calendário (Data/Hora)  

Manter Usuários
- O Usuário logado poderá ver quais eventos ele se inscreveu, participou e se inscrever em outros eventos disponíveis e cancelar a inscrição.
- O usuário poderá realizar um post sobre comentários sobre o minicurso passível de aprovação previa.

#Firulas
O sistema ter rotinas de aviso aos inscritos sobre alterações no evento e lembrete.

Germano, de cabeça é isso... qq c acha? vou desenhar um papel de pão e mando.
